"""empty message

Revision ID: 28b20d917a9a
Revises: eac8dfe37978
Create Date: 2023-08-15 09:08:39.487972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b20d917a9a'
down_revision: Union[str, None] = 'eac8dfe37978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'salom')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('salom', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
