"""empty message

Revision ID: b70f84303435
Revises: c0f9edf6fc5b
Create Date: 2023-08-15 09:11:36.847371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70f84303435'
down_revision: Union[str, None] = 'c0f9edf6fc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('join_data', sa.String(), nullable=True))
    op.add_column('works', sa.Column('complete_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'complete_data')
    op.drop_column('works', 'join_data')
    # ### end Alembic commands ###
