"""empty message

Revision ID: c0f9edf6fc5b
Revises: dd868c937299
Create Date: 2023-08-15 09:10:53.703579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f9edf6fc5b'
down_revision: Union[str, None] = 'dd868c937299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'complete_data')
    op.drop_column('works', 'join_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('join_data', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('complete_data', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
