"""empty message

Revision ID: dd868c937299
Revises: 53c9c195a45c
Create Date: 2023-08-15 09:09:51.513981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd868c937299'
down_revision: Union[str, None] = '53c9c195a45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'join_data')
    # ### end Alembic commands ###
